# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- main
#- Test*
    
# schedules:
#   - cron: "00 15 04 * *"
#     displayName: testing build
#     branches:
#       include:
#         - develop
#         - release-2*
#     always: false

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo I am Vinay
  displayName: 'Run a multi-line script'
